config/routes.rb
SeatYourself::Application.routes.draw do
 root 'restaurants#index'

 resources :restaurants do
  resources :reservations
  end
 resources :users 
 resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :reviews
  has_many :restaurants, through: :reservations
  has_secure_password

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_length_of :password, minimum: 6, too_short: 'Please enter a password with at least 6 characters' 
  validates :first_name, presence: true
  validates :last_name, presence: true



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @title = "Users"
    @users = User.all
  end

  def show
    @title = "Users"
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to users_path    
      flash[:notice] = "User was successfully created"
    else
      flash[:alert] = "User could not be created."
      render :new
    end
  end

  def new
    @title = "Add User"
    @title = "Add a User"
    @user = User.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
      flash[:notice] = "Congratulations - User updated ;)"
    else
      flash[:alert] = "Sorry I'm being an arse, user not updated."
      render :new
    end
  end

  def edit
    @title = "Edit a User"
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
      flash[:notice] = "User is dead."
    else
      flash[:notice] = "User is zombie. Cannot kill what is already dead!"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name %><br />

<%= f.label :last_name %>
<%= f.text_field :last_name %><br />

<%= f.label :email %>
<%= f.email_field :email %><br />

<%= f.label :password %>
<%= f.password_field :password %><br />

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br />

<%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
<p><%= user.first_name %> <%= user.last_name %></p>
<%= link_to "Show User", user_path(user) %>
<% end %>

</br>
</br>
<h4><%= link_to "Give birth!", new_user_path %></h4>

app/views/users/new.html.erb
<h1>Add a User</h1>

<%= form_for @user do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name %><br />

<%= f.label :last_name %>
<%= f.text_field :last_name %><br />

<%= f.label :email %>
<%= f.email_field :email %><br />

<%= f.label :password %>
<%= f.password_field :password %><br />

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br />

<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name + " " + @user.last_name %></h1>
<%= link_to "Edit me biatch!", edit_user_path %> <%= link_to "Kill that muthafucker!", @user, method: :delete %>


<p>User's email address: <%= @user.email %></p>

<h2>Reservations</h2>

<ul>
  <% @user.reservations.each do |reservation| %>

  <li>
    <h3><%= reservation.restaurant.name %></h3>
    <p><%= reservation.restaurant.address %></p>

    <p>Guests: <%= reservation.guests %> | Time: <%= reservation.time.hour %>:00 | Date: <%= reservation.date %> | Duration: <%= reservation.duration %> hours</p>

    <p><%= link_to "Edit Reservation", edit_restaurant_reservation_path(reservation.restaurant, reservation.id) %> |
    <%= link_to "Delete Reservation", [reservation.restaurant, reservation], confirm: "Are you sure you want to delete this reservation?", method: :delete %>


  </li>

  <% end %>

</ul>