config/routes.rb
SeatYourself::Application.routes.draw do
 root 'restaurants#index'

 resources :restaurants do
  resources :reservations
  end
 resources :users 
 resources :sessions, only: [:new, :create, :destroy]

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  require 'tod'

  belongs_to :cuisine
  has_many :reservations
  has_many :users, through: :reservations
  has_many :reviews
  has_many :timeslots


  def parse_time(hour, minute)
    TimeOfDay.new(hour.to_i,minute.to_i).strftime("%H:%M")
  end

  def unparse_time(time)
    time = TimeOfDay.parse time
    time.on Date.new
  end

  def show_available_seats(timeslot)
    seats = self.timeslots.where(restaurant_id: self.id, date: timeslot.date, time:timeslot.time)
    self.capacity - seats.first.seats
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_filter :ensure_logged_in, only: [:new, :create, :edit, :update, :destroy]

  def index
    @title = "Restaurants"
    @restaurants = Restaurant.all

  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.opening_time = @restaurant.parse_time(params[:restaurant]["opening_time(4i)"], params[:restaurant]["opening_time(5i)"])
    @restaurant.closing_time = @restaurant.parse_time(params[:restaurant]["closing_time(4i)"], params[:restaurant]["closing_time(5i)"])
    
    if @restaurant.save
      redirect_to restaurants_path    
      flash[:notice] = "BOOM! Restaurant created, yo."
    else
      flash[:alert] = "Idiot. I can't create a restaurant with invalid fields. Duh."
      render :new
    end
  end

  def new
    @title = "Add a Restaurant"
    @restaurant = Restaurant.new
    @cuisine = Cuisine.all
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.opening_time = @restaurant.parse_time(params[:restaurant]["opening_time(4i)"], params[:restaurant]["opening_time(5i)"])
    @restaurant.closing_time = @restaurant.parse_time(params[:restaurant]["closing_time(4i)"], params[:restaurant]["closing_time(5i)"])
    
    if @restaurant.update_attributes(restaurant_params)
      redirect_to @restaurant
      flash[:notice] = "YEAAAHHH!! Restaurant was successfully updated. Woo..fucking..hoo"
    else
      flash[:alert] = "Dude, WTF?! This shitty (probably Chinese) restaurant failed to update."
      render :edit
    end
  end

  def edit
    @title = "Edit a Restaurant"
    @restaurant = Restaurant.find(params[:id])
    @restaurant.opening_time = @restaurant.unparse_time(@restaurant.opening_time)
    @restaurant.closing_time = @restaurant.unparse_time(@restaurant.closing_time)

  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    
    if @restaurant.destroy
      redirect_to restaurants_path
      flash[:notice] = "You killed that muthafucking Restaurant!"
    else
      flash[:alert] = "You can't delete a non-existent restaurant, sucka!"
      redirect_to restaurants_path
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :price_range, :cuisine_id, :capacity)
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />

  <%= f.label :address %><br />
  <%= f.text_area :address, size: "50x10" %><br />

  <%= f.label :price_range %><br />
  <%= f.select(:price_range, [['Low ($0 - $10)', "Low"], ['Medium ($10 - $30)', "Medium"], ['High ($30+)', "High"]]) %><br />

  <%= f.label :cuisine_id %><br />
  <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :name) %><br />

  <%= f.label :capacity %><br />
  <%= f.text_field :capacity %><br />

  <%= f.label :opening_time %><br />
  <%= f.time_select :opening_time, {ampm: true, ignore_date: true, minute_step: 15, default: {:hour => '09', :minute => '00'}}  %> <br />

  <%= f.label :closing_time %><br />
  <%= f.time_select :closing_time, {ampm: true, ignore_date: true, minute_step: 15, default: {:hour => '22', :minute => '00'}}  %><br />
  <br />
  <%= f.submit %>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />

  <%= f.label :address %><br />
  <%= f.text_area :address, size: "50x10" %><br />

  <%= f.label :price_range %><br />
  <%= f.select(:price_range, [['Low ($0 - $10)', "Low"], ['Medium ($10 - $30)', "Medium"], ['High ($30+)', "High"]]) %><br />

  <%= f.label :cuisine_id %><br />
  <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :name) %><br />

  <%= f.label :capacity %><br />
  <%= f.text_field :capacity %><br />

  <%= f.label :opening_time %><br />
  <%= f.time_select :opening_time, {ampm: false, ignore_date: true, minute_step: 15 }  %> <br />

  <%= f.label :closing_time %><br />
  <%= f.time_select :closing_time, {ampm: false, ignore_date: true, minute_step: 15 }  %><br />
  <br />
  <%= f.submit %>

<% end %>

app/views/restaurants/index.html.erb
<div class="row">
	<div class="large-12 columns">
		<ul data-orbit>
			<li><%= image_tag("duck.jpg") %></li>
			<li><%= image_tag("pizza.jpg") %></li>
			<li><%= image_tag("sushi.jpg") %></li>
		</ul>
	</div>
</div>

<div class="row">
<!-- 	<div class="large-3 large-offset-3 columns">
	</div> -->

	<div class="large-8 large-centered columns">
		<!-- <div class="large-2 columns"> -->
			<a href="#" class="default button dropdown">Cuisine</a>
			<!-- 		<ul class="large success button dropdown">
			<li>Chinese</li>
			<li>Italian</li>
			<li>Japanese</li> -->
		<!-- </div> -->
		<!-- <div class="large-2 columns"> -->
			<a href="#" class="default button dropdown">Neighbourhood</a>
			<a href="#" class="default button dropdown">Price Range</a>
			<a href="#" class="button success">Search</a>
		<!-- </div> -->
	</div>
<!-- 	<div class="large-3 large-offset-3 columns">
	</div> -->
</div>

<hr />

<div class="row">
	<div class="large-12 columns">
		<h1>Restaurants</h1>
		  <%  @restaurants.each do |restaurant| %>
		  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2><br />
		  <p class="cuisine"><%= restaurant.cuisine.name %></p>
		  <p class="open-until">Open from: <%= restaurant.opening_time %> - <%= restaurant.closing_time %></p>
		  <p class="price-range">Price: <%= restaurant.price_range %></p>
		  <p class="address">Address:<br /><%= restaurant.address %></p>
		  <% end %>

		  <%= link_to "Create Restaurant", new_restaurant_path %>
	</div>
</div>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />

  <%= f.label :address %><br />
  <%= f.text_area :address, size: "50x10" %><br />

  <%= f.label :price_range %><br />
  <%= f.select(:price_range, [['Low ($0 - $10)', "Low"], ['Medium ($10 - $30)', "Medium"], ['High ($30+)', "High"]]) %><br />

  <%= f.label :cuisine_id %><br />
  <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :name) %><br />

  <%= f.label :capacity %><br />
  <%= f.text_field :capacity %><br />

  <%= f.label :opening_time %><br />
  <%= f.time_select :opening_time, {ampm: false, ignore_date: true, minute_step: 15, default: {:hour => '09', :minute => '00'}} %><br />

  <%= f.label :closing_time %><br />
  <%= f.time_select :closing_time, {ampm: false, ignore_date: true, minute_step: 15, default: {:hour => '23', :minute => '00'}} %><br />

  <br />
  <%= f.submit %>

<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<ul>

  <% @restaurant.timeslots.each do |timeslot| %>
  <li><%= timeslot.date %> has <%= @restaurant.show_available_seats(timeslot) %> seats avaliable at <%= timeslot.time %>:00</li>
  <% end %>
</ul>

<%= link_to "Edit Restaurant", edit_restaurant_path %>
<%= link_to "Delete Restaurant", @restaurant, method: :delete %>
<%= link_to "Create Reservation", new_restaurant_reservation_path(@restaurant) %>