config/routes.rb
SeatYourself::Application.routes.draw do
 root 'restaurants#index'

 resources :restaurants do
  resources :reservations
  end
 resources :users 
 resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
  	<meta charset="utf-8" />
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "sEATyourself" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-4 columns">
        <h1 class="logo"><%= image_tag("logo.png") %></h1>
      </div>
      <div class="large-8 columns">
        <div class="right button-group">
          <% if current_user %>
            <li class="button"><%= link_to "Logout #{current_user.first_name}", session_path(current_user), method: :delete %></li>
            <li class="button"><%= link_to "Profile", user_path(params[:id]) %>
          <% else %>
            <li class="button"><%= link_to "Login", new_session_path %></li>
            <li class="button"><%= link_to "Signup", new_user_path %></li>
          <% end %>
        </div>
      </div>
    </div>

  <div class="row">
    <% flash.each do |key, value| %>
      <div class="<%= key %>"><%= value %></div>
    <% end %>
  </div>
<!--   <div id="container"> -->
  <div class="row">
    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>
  </body>
</html>